### ISSUE TITLE
Error when page contains %%//%%

### ISSUE THREAD

**Issue by nostikj** [jean-michel-gonet/dokuwiki-plugin-latexport#35]
I'm getting an error (seqfault) when my input page has %%//%% as part of the text.

**Comment by jean-michel-gonet** [comment]
Hi nostikj:
- Can you paste me an excerpt of the page content?
- Does it fail during the ZIP file generation, or during the latex processing?

**Comment by jean-michel-gonet** [comment]
Right. I could reproduce this error
