### ISSUE TITLE
Issue with Configuration Settings after installing

### ISSUE THREAD

**Issue by mkha98** [jean-michel-gonet/dokuwiki-plugin-latexport#38]
Two questions:
 a.) Where do I make the "Anchor Hack" laid out on the description page? I'm trying to figure out which file has the method in question.
 
b.) After installing the plugin, I'm getting the following when I try to navigate to "Configuration Settings"

![Screen Shot 2020-04-13 at 1 14 38 PM](https://user-images.githubusercontent.com/63605940/79141990-d45b5100-7d88-11ea-92be-6c3cd1318699.jpg)

**Comment by jean-michel-gonet** [comment]
Hi. Thanks for reporting. I'm going to check this.

**Comment by jean-michel-gonet** [comment]
Closing this issue:
- New version 1.0.4 available
- Updated the download link at: https://www.dokuwiki.org/plugin:latexport
- Also updated the instructions about the _Anchor_ plugin.
